name: CI
on: 
  push: 
    branches: main
  pull_request: 
    branches: '*'
env:
    SONAR_SCANNER_OPTS: "-Dsonar.scanner.skipJreProvisioning=true"
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Cache files 
        uses: actions/cache@v4
        with: 
            path: | 
                ~/.sonar 
            key: ${{ runner.os }}-sonar 
            restore-keys: ${{ runner.os }}-sonar 
      - name: Run Codescan On Push 
        if: github.event_name == 'push' 
        uses: codescan-io/codescan-scanner-action@prerelease-test
        with: 
          organization: sush
          projectKey: cd-6610-github3
          codeScanUrl: https://test.codescan.io/
          login: squ_6f58e0b8e08435553db7d8165df2fbf9af1ab812
          generateSarifFile: false 
          failOnRedQualityGate: true 
          args: 
            sonar.scanner.skipJreProvisioning=true
      - name: Run Codescan On PR 
        if: github.event_name == 'pull_request' 
        uses: codescan-io/codescan-scanner-action@prerelease-test
        with: 
          organization: sush
          projectKey: cd-6610-github3
          codeScanUrl: https://test.codescan.io/
          login: squ_6f58e0b8e08435553db7d8165df2fbf9af1ab812
          scanChangedFilesOnly: true 
          generateSarifFile: false 
          failOnRedQualityGate: true 
          args: | 
            sonar.scanner.skipJreProvisioning=true
            sonar.pullrequest.branch=${{github.head_ref}} 
            sonar.pullrequest.base=${{github.base_ref}} 
            sonar.pullrequest.key=${{github.event.number}} 
      - name: Upload SARIF file 
        uses: github/codeql-action/upload-sarif@v3 
        with: 
          sarif_file: codescan.sarif 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: codescan.sarif
          path: codescan.sarif
